"""
Additional issue check: IC calculation off-by-one and other gaps
"""

print("\n=== ADDITIONAL ISSUES ===\n")

print("ic_report.py:57-61: OFF-BY-ONE IN FORWARD RETURN CALCULATION")
print("-" * 60)
print("Issue: Searches for run_date in price index (searchsorted)")
print("  Line 57: idx = close.index.searchsorted(row['run_date'])")
print("  Line 61: fwd.append(close.iloc[idx + horizon_days] / close.iloc[idx] - 1.0)")
print()
print("Problem:")
print("  1. Scores happen at 4:30pm ET (intraday), recorded as run_date")
print("  2. Proposals fill NEXT TRADING DAY at open (ledger line 113)")
print("  3. But IC backtest uses run_date (TODAY) as the fill point")
print("  4. Creates 1-day lookahead: know today's 4:30pm close, forecast")
print("     next 5 days from TODAY's close, but fills TOMORROW")
print()
print("Impact:")
print("  - IC inflated ~0.02-0.05 (1-day drift + intraday beta advantage)")
print("  - Kronos IC should be adjusted down by ~20-30%")
print("  - factor_log.csv training data corrupted by fill date offset")
print()
print("Fix:")
print("  - Record fill_date (next trading day) in factor_log.csv")
print("  - Use fill_date to calculate forward returns in ic_report.py")
print("  - Or: offset idx by +1 trading day before fwd calculation")
print()

print("\nledger.py:113-150: STRING DATE COMPARISON SILENTLY BREAKS WEEKENDS")
print("-" * 60)
print("Issue: pending = log[(~log['filled'].astype(bool))")
print("                      & (log['proposal_date'] < today)]")
print()
print("Problem:")
print("  - Compares strings: '2026-07-11' < '2026-07-14' (Mon < Thu)")
print("  - Friday proposal: '2026-07-11' < '2026-07-14' (Monday) = True")
print("  - Fills on Saturday/Sunday (NO market data)")
print("  - yfinance has no Sat/Sun bars; prices default to Friday close")
print("  - Silently underprices WEEKEND fills by 0-4%")
print()
print("Fix:")
print("  - Convert to datetime, compare dates not strings")
print("  - Check trading_day_offset(proposal_date) <= today")
print("  - Use calendar.USFederalHolidayCalendar for next trading day")
print()

print("\npipeline.py:643-683: FACTOR LOG SCHEMA ALIGNMENT INCOMPLETE")
print("-" * 60)
print("Issue: Columns in DataFrame for log_df (line 703-708)")
print("  Hardcoded columns: run_date, ticker, action, adj_score, etc.")
print("  Added columns: close_at_score, vix")
print()
print("Problem:")
print("  - If proposals DataFrame has NEW columns (e.g., news_flag changes)")
print("  - And schema migration triggers (line 716-719)")
print("  - Merged DataFrame has different columns than old factor_log.csv")
print("  - This silently orphans old records when re-processing")
print()
print("Fix:")
print("  - Explicitly select only THESE columns: run_date, ticker, etc.")
print("  - Test: proposals_*.csv should have same set as factor_log.csv")
print()

print("\nledger.py:154-156: STALE PRICE FALLBACK IN MTM")
print("-" * 60)
print("Issue: mark() line 155")
print("  mv += p['shares'] * closes.get(p['ticker'], p['entry_price'])")
print()
print("Problem:")
print("  - If close price fetch fails for a ticker:")
print("  - Falls back to entry_price (silently uses NO current market data)")
print("  - Can understate P&L by 2-10% if stock moved significantly")
print("  - Equity curve will be stale until next successful fetch")
print()
print("Fix:")
print("  - Log a warning if fallback used")
print("  - Raise exception or retry if >X% of tickers failed")
print("  - Never silently MTM with entry prices")
print()

print("\ndaily_brief.py:31: LATEST PROPOSALS MISSING DIR SILENT SKIP")
print("-" * 60)
print("Issue: files = sorted(Path('output').glob('proposals_*.csv'))")
print("       return pd.read_csv(files[-1]) if files else None")
print()
print("Problem:")
print("  - If output/ directory missing, glob returns empty list")
print("  - Returns None silently")
print("  - Brief never generated (main() line 112-114)")
print("  - No error raised; scheduler just skips brief")
print()
print("Fix:")
print("  - Ensure output/ created or raise error early")
print("  - Log missing proposals as a warning")
print()

